name: Deploy Documentation

on:
  push:
    branches: [ main ] # Ou a branch principal do seu repositório 'docs'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Certifique-se que esta versão do Python é compatível com seus plugins

      - name: Install dependencies
        run: |
          pip install -r requirements.txt # Você precisará criar este arquivo!

      - name: Build documentation
        run: |
          mkdocs build --strict # O --strict faz o build falhar se houver avisos

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site' # Pasta onde o mkdocs build gera os arquivos HTML

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Este job só roda depois que o job 'build' for bem-sucedido
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
